import Foundation

enum ShadowAPIError: Error, LocalizedError { case badURL, nodeUnreachable, server(Int, String), decoding, notPaired; var errorDescription: String? { String(describing: self) } }
protocol ShadowAPIClient { var baseURL: URL { get set }; func health() async throws -> EmergencyPauseState; func pairStart() async throws -> PairingChallenge; func pairConfirm(challenge: PairingChallenge, deviceName: String, publicKey: String) async throws -> DeviceIdentity; func grantConsent(dataSource: String, scope: String, purpose: String) async throws -> ConsentGrant; func ingestMemory(text: String, sourceTitle: String) async throws -> [MemoryItem]; func searchMemory(_ query: String) async throws -> [MemorySearchResult]; func ask(_ prompt: String) async throws -> AgentAskResponse; func createApproval(action: AgentAction, reason: String) async throws -> ApprovalRequest; func approvals() async throws -> [ApprovalRequest]; func approve(id: String) async throws -> ApprovalRequest; func deny(id: String, reason: String) async throws -> ApprovalRequest; func execute(action: AgentAction, approved: Bool, doubleConfirmed: Bool) async throws -> String; func devices() async throws -> [Device]; func audit() async throws -> [AuditEvent]; func setEmergencyPause(_ paused: Bool, reason: String?) async throws -> EmergencyPauseState }
final class ShadowNodeAPIClient: ShadowAPIClient {
    var baseURL: URL; var mockMode: Bool; private let session: URLSession; private let store: DeviceIdentityStoring; private let signer = ShadowRequestSigner(); private let decoder = JSONDecoder(); private let encoder = JSONEncoder()
    init(baseURL: URL, mockMode: Bool = true, store: DeviceIdentityStoring = KeychainDeviceIdentityStore()) { self.baseURL = baseURL; self.mockMode = mockMode; self.store = store; let cfg = URLSessionConfiguration.default; cfg.timeoutIntervalForRequest = 12; self.session = URLSession(configuration: cfg); decoder.keyDecodingStrategy = .useDefaultKeys; decoder.dateDecodingStrategy = .iso8601; encoder.keyEncodingStrategy = .useDefaultKeys; encoder.dateEncodingStrategy = .iso8601 }
    func health() async throws -> EmergencyPauseState { if mockMode { return EmergencyPauseState(paused: false) }; let value: HealthResponse = try await request("GET", "/health", auth: false); return EmergencyPauseState(paused: value.emergencyPaused) }
    func pairStart() async throws -> PairingChallenge { if mockMode { return PairingChallenge(pairingId: "mock_pair", code: "MOCK42", expiresInSeconds: 300) }; return try await request("POST", "/pair/start", auth: false) }
    func pairConfirm(challenge: PairingChallenge, deviceName: String, publicKey: String) async throws -> DeviceIdentity { if mockMode { let id = DeviceIdentity(deviceId: "mock_device", sharedSecret: "mock_secret", nodeFingerprint: "mock_node", publicKey: publicKey, baseURL: baseURL); store.save(id); return id }; let body = PairConfirmBody(pairing_id: challenge.pairingId, device_name: deviceName, public_key: publicKey); let response: PairConfirmResponse = try await request("POST", "/pair/confirm", body: body, auth: false); let id = DeviceIdentity(deviceId: response.device.id, sharedSecret: response.shared_secret, nodeFingerprint: response.device.fingerprint ?? "", publicKey: publicKey, baseURL: baseURL); store.save(id); return id }
    func grantConsent(dataSource: String, scope: String, purpose: String) async throws -> ConsentGrant { try await request("POST", "/consent", body: ConsentBody(data_source: dataSource, scope: scope, purpose: purpose, model_access_level: "local_only"), auth: true) }
    func ingestMemory(text: String, sourceTitle: String) async throws -> [MemoryItem] { if mockMode { return [MemoryItem(id: UUID().uuidString, type: "document_chunk", category: "note", text: text, source: MemorySource(id: "mock_source", kind: "manual", title: sourceTitle, uri: nil, consentGrantId: nil), tags: [], confidence: 0.9, sensitive: false, doNotSendToCloud: false)] }; let response: IngestResponse = try await request("POST", "/memory/ingest", body: IngestBody(text: text, source_kind: "ios_manual", source_title: sourceTitle), auth: true); return response.items }
    func searchMemory(_ query: String) async throws -> [MemorySearchResult] { if mockMode { return [] }; return try await request("GET", "/memory/search?q=\(query.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed) ?? query)", auth: true) }
    func ask(_ prompt: String) async throws -> AgentAskResponse { if mockMode { return AgentAskResponse(answer: "Mock local answer", sources: [], why: ["Mock mode"], modelUsed: "local_mock", cloudAllowed: false, untrustedContext: true, plan: nil) }; return try await request("POST", "/agent/ask", body: AskBody(prompt: prompt, allow_cloud: false, cloud_approval: false), auth: true) }
    func createApproval(action: AgentAction, reason: String) async throws -> ApprovalRequest { try await request("POST", "/approvals", body: ApprovalCreateBody(action: action, reason: reason), auth: true) }
    func approvals() async throws -> [ApprovalRequest] { if mockMode { return [] }; return try await request("GET", "/approvals", auth: true) }
    func approve(id: String) async throws -> ApprovalRequest { try await request("POST", "/approvals/\(id)/approve", auth: true) }
    func deny(id: String, reason: String) async throws -> ApprovalRequest { try await request("POST", "/approvals/\(id)/deny", body: DenyBody(reason: reason), auth: true) }
    func execute(action: AgentAction, approved: Bool, doubleConfirmed: Bool) async throws -> String { let value: GenericJSON = try await request("POST", "/agent/execute", body: ExecuteBody(action: action, approved: approved, double_confirmed: doubleConfirmed), auth: true); return value.description }
    func devices() async throws -> [Device] { if mockMode { return [] }; return try await request("GET", "/devices", auth: true) }
    func audit() async throws -> [AuditEvent] { if mockMode { return [] }; return try await request("GET", "/audit", auth: true) }
    func setEmergencyPause(_ paused: Bool, reason: String?) async throws -> EmergencyPauseState { if mockMode { return EmergencyPauseState(paused: paused) }; return try await request("POST", "/emergency_pause", body: EmergencyPauseBody(paused: paused, reason: reason), auth: true) }
    private func request<T: Decodable>(_ method: String, _ path: String, auth: Bool) async throws -> T { try await request(method, path, bodyData: Data(), auth: auth) }
    private func request<T: Decodable, B: Encodable>(_ method: String, _ path: String, body: B, auth: Bool) async throws -> T { try await request(method, path, bodyData: encoder.encode(body), auth: auth) }
    private func request<T: Decodable>(_ method: String, _ path: String, bodyData: Data, auth: Bool) async throws -> T { guard let url = URL(string: path, relativeTo: baseURL) else { throw ShadowAPIError.badURL }; var req = URLRequest(url: url); req.httpMethod = method; if !bodyData.isEmpty { req.httpBody = bodyData; req.setValue("application/json", forHTTPHeaderField: "Content-Type") }; if auth { guard let identity = store.load() else { throw ShadowAPIError.notPaired }; signer.headers(identity: identity, method: method, path: URLComponents(url: url, resolvingAgainstBaseURL: true)?.path ?? path, body: bodyData).forEach { req.setValue($0.value, forHTTPHeaderField: $0.key) } }; let (data, response) = try await session.data(for: req); let code = (response as? HTTPURLResponse)?.statusCode ?? 0; guard (200..<300).contains(code) else { throw ShadowAPIError.server(code, String(data: data, encoding: .utf8) ?? "") }; return try decoder.decode(T.self, from: data) }
}
struct HealthResponse: Codable { var emergencyPaused: Bool; enum CodingKeys: String, CodingKey { case emergencyPaused = "emergency_paused" } }
struct PairConfirmBody: Codable { var pairing_id: String; var device_name: String; var public_key: String }
struct PairConfirmResponse: Codable { var device: Device; var shared_secret: String }
struct ConsentBody: Codable { var data_source: String; var scope: String; var purpose: String; var model_access_level: String }
struct IngestBody: Codable { var text: String; var source_kind: String; var source_title: String }
struct IngestResponse: Codable { var source: MemorySource; var items: [MemoryItem] }
struct AskBody: Codable { var prompt: String; var allow_cloud: Bool; var cloud_approval: Bool }
struct ApprovalCreateBody: Codable { var action: AgentAction; var reason: String }
struct DenyBody: Codable { var reason: String }
struct ExecuteBody: Codable { var action: AgentAction; var approved: Bool; var double_confirmed: Bool }
struct EmergencyPauseBody: Codable { var paused: Bool; var reason: String? }
struct GenericJSON: Decodable, CustomStringConvertible { let description: String; init(from decoder: Decoder) throws { self.description = "Execution response received" } }
