/**
 * App Intents runtime wiring (Siri / Spotlight / Shortcuts on iOS,
 * Assistant / App Actions on Android).
 *
 * Native surfaces are generated by `npx app-intents generate`
 * (config: app-intents.config.ts) and by the Expo config plugin at
 * prebuild time. When an intent fires, the OS opens
 * `shadow://app-intents/<intentId>?payload=<json>`; this module routes
 * the intent to the right in-app action.
 *
 * In Expo Go (no native module) everything degrades to a no-op: setup
 * catches the failure and the app behaves as before.
 */

import * as Linking from "expo-linking";
import { router } from "expo-router";
import {
	createAppIntentsRuntime,
	type IntentEventUnion,
} from "@avasapp/react-native-app-intents";
import { openShadow, shadowIntents } from "../intents/shadow.intents";
import { routeForIntent, type IntentRoute } from "./intentRouting";
import { useChatStore } from "../stores/useChatStore";
import { useProviderStore } from "../stores/useProviderStore";

async function executeRoute(route: IntentRoute): Promise<void> {
	switch (route.kind) {
		case "open":
			router.replace("/(tabs)/chat");
			return;
		case "unknown":
			return;
		case "ask":
		case "remember": {
			const { providerId, modelId } = useProviderStore.getState();
			const message =
				route.kind === "ask" ? route.prompt : `Remember this: ${route.text}`;
			try {
				const threadId = await useChatStore.getState().createThread(providerId, modelId);
				router.push({
					pathname: "/chat/[id]",
					params: { id: threadId, autosend: message },
				});
			} catch {
				router.replace("/(tabs)/chat");
			}
		}
	}
}

let started = false;

/**
 * Subscribe to App Intent invocations. Safe to call once from the root
 * layout; resolves after the cold-start intent (if any) is routed.
 * Never throws.
 */
export async function setupAppIntents(): Promise<void> {
	if (started) return;
	started = true;
	try {
		const runtime = createAppIntentsRuntime({
			scheme: "shadow",
			intents: shadowIntents,
			linking: {
				addEventListener: (event, listener) => Linking.addEventListener(event, listener),
				getInitialURL: () => Linking.getInitialURL(),
			},
		});

		const handle = (event: IntentEventUnion<typeof shadowIntents>) => {
			void executeRoute(routeForIntent(event));
		};

		// Cold start: the OS may have opened us with an intent URL.
		try {
			const initial = await runtime.getInitialIntent();
			if (initial) handle(initial);
		} catch {
			// No pending intent; normal launch.
		}

		runtime.onAnyIntent(handle);

		// Donate the launcher so Siri Suggestions can offer it.
		try {
			await runtime.donate(openShadow, {});
		} catch {
			// Donations are best-effort.
		}
	} catch {
		// Native module absent (Expo Go) or runtime unavailable.
	}
}
