import Foundation

enum AutonomyMode: String, CaseIterable, Codable, Identifiable { case off, suggestOnly = "suggest_only", draftOnly = "draft_only", executeWithApproval = "execute_with_approval", trustedWorkflow = "trusted_workflow", fullAutonomousDisabled = "full_autonomous_disabled"; var id: String { rawValue } }
enum RiskClass: String, Codable { case low, medium, high, blocked }
enum ApprovalStatus: String, Codable { case pending, approved, denied, expired }
struct PairingChallenge: Codable { var pairingId: String; var code: String; var expiresInSeconds: Int; enum CodingKeys: String, CodingKey { case pairingId = "pairing_id", code, expiresInSeconds = "expires_in_seconds" } }
struct Device: Identifiable, Codable { var id: String; var name: String; var publicKey: String?; var fingerprint: String?; var trusted: Bool; var revoked: Bool?; var sessionExpiresAt: Date?; enum CodingKeys: String, CodingKey { case id, name, trusted, revoked, fingerprint, publicKey = "public_key", sessionExpiresAt = "session_expires_at" } }
struct ConsentGrant: Identifiable, Codable { var id: String; var dataSource: String; var scope: String; var purpose: String; var modelAccessLevel: String; enum CodingKeys: String, CodingKey { case id, dataSource = "data_source", scope, purpose, modelAccessLevel = "model_access_level" } }
struct MemorySource: Identifiable, Codable { var id: String; var kind: String; var title: String; var uri: String?; var consentGrantId: String?; enum CodingKeys: String, CodingKey { case id, kind, title, uri, consentGrantId = "consent_grant_id" } }
struct MemoryItem: Identifiable, Codable { var id: String; var type: String?; var category: String?; var text: String; var source: MemorySource; var tags: [String]?; var confidence: Double; var sensitive: Bool?; var doNotSendToCloud: Bool?; enum CodingKeys: String, CodingKey { case id, type, category, text, source, tags, confidence, sensitive, doNotSendToCloud = "do_not_send_to_cloud" } }
struct MemorySearchResult: Identifiable, Codable { var id: String { item.id }; var item: MemoryItem; var score: Double; var freshness: Double; var attribution: String; var explanation: String; var untrustedContext: Bool?; enum CodingKeys: String, CodingKey { case item, score, freshness, attribution, explanation, untrustedContext = "untrusted_context" } }
struct AgentAction: Identifiable, Codable { var id: String; var toolName: String; var description: String; var params: [String:String]?; var risk: RiskClass?; var requiresApproval: Bool?; var destructive: Bool?; var destination: String?; var dataUsed: [String]?; var modelUsed: String?; enum CodingKeys: String, CodingKey { case id, description, params, risk, destructive, destination, toolName = "tool_name", requiresApproval = "requires_approval", dataUsed = "data_used", modelUsed = "model_used" } }
struct AgentPlan: Identifiable, Codable { var id: String; var userIntent: String; var actions: [AgentAction]; var requiresCloud: Bool?; var rationale: String?; enum CodingKeys: String, CodingKey { case id, actions, rationale, userIntent = "user_intent", requiresCloud = "requires_cloud" } }
struct AgentAskResponse: Codable { var answer: String; var sources: [MemorySearchResult]; var why: [String]; var modelUsed: String?; var cloudAllowed: Bool?; var untrustedContext: Bool?; var plan: AgentPlan?; enum CodingKeys: String, CodingKey { case answer, sources, why, plan, modelUsed = "model_used", cloudAllowed = "cloud_allowed", untrustedContext = "untrusted_context" } }
struct ApprovalRequest: Identifiable, Codable { var id: String; var action: AgentAction; var reason: String; var actionPreview: String?; var dataUsedPreview: [String]?; var modelUsedPreview: String?; var destinationPreview: String?; var riskLabel: RiskClass?; var requiresDoubleConfirmation: Bool?; var status: ApprovalStatus; var denyReason: String?; enum CodingKeys: String, CodingKey { case id, action, reason, status, actionPreview = "action_preview", dataUsedPreview = "data_used_preview", modelUsedPreview = "model_used_preview", destinationPreview = "destination_preview", riskLabel = "risk_label", requiresDoubleConfirmation = "requires_double_confirmation", denyReason = "deny_reason" } }
struct AuditEvent: Identifiable, Codable { var id: String; var actor: String; var eventType: String; var status: String; var result: String?; var timestamp: Date?; var proposedAction: String?; enum CodingKeys: String, CodingKey { case id, actor, status, result, timestamp, eventType = "event_type", proposedAction = "proposed_action" } }
struct EmergencyPauseState: Codable { var paused: Bool }
